import sqlite3

db = sqlite3.connect('users.db')
cur = db.cursor()
#
# cur.execute("""ALTER TABLE users ADD COLUMN gender TEXT DEFAULT ('')""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN phone TEXT DEFAULT ('')""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN city TEXT DEFAULT ('')""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN birth TEXT DEFAULT ('')""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN mail TEXT DEFAULT ('')""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN flag_pers BIGINT DEFAULT (0)""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN pay_pack_1 BIGINT DEFAULT (0)""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN flag_name BIGINT DEFAULT (1)""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN flag_phone BIGINT DEFAULT (0)""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN flag_city BIGINT DEFAULT (0)""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN flag_mail BIGINT DEFAULT (0)""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN flag_birth BIGINT DEFAULT (0)""")
# db.commit()
# cur.execute("""ALTER TABLE users ADD COLUMN flag_les_all BIGINT DEFAULT (0)""")
# db.commit()
cur.execute("""ALTER TABLE users ADD COLUMN module BIGINT DEFAULT (0)""")
db.commit()
